{
 "title": "Flask Monitoring Dashboard",
 "tags": [
  "flask",
  "prometheus",
  "docker"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(flask_http_request_total)", "legendFormat": "Requests" }
   ]
  },
  {
   "title": "HTTP Requests Over Time",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m]))",
     "legendFormat": "req/s"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status!~\"2..\"}[1m])) / sum(rate(flask_http_request_total[1m])) * 100",
     "legendFormat": "Error %"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"flask_app\"}[1m]) * 100",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container=\"flask_app\"} / 1024 / 1024",
     "legendFormat": "Memory MB"
    }
   ]
  }
 ]
}